### ISSUE TITLE
Create a folder structure for chapters

### ISSUE THREAD

**Issue by MOJOliciousFTW** [MOJOliciousFTW/workshop-github-2024#1]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when collaborating on a single document and ending up with merge conflicts.

**Describe the solution you'd like**
A folder named Paper, with subfolders named 01_Introduction, 02_Method, 03_Results, 04_Discussion.

**Describe alternatives you've considered**
Working on one file, SMH, life's too short.

**Additional context**

**Comment by MOJOliciousFTW** [comment]
Ready to work on. Acceptance criteria: Folder structure in main.

**Comment by Emil-Waldemar** [comment]
ferdig med denne og lagt til review
