### ISSUE TITLE
Add text

### ISSUE THREAD

**Issue by MOJOliciousFTW** [MOJOliciousFTW/workshop-github-2024#4]
Add text to chapters

Needs:
- [x] #1 

Then:
- [x] Add text to 01_Introduction
- [x] Add text to 02_Method
- [ ] Add text to 03_Result
- [ ] Add text to 04_Discussion

**Comment by rangorC** [comment]
@MOJOliciousFTW  I need the access plz

**Comment by MOJOliciousFTW** [comment]
LGTM
