### ISSUE TITLE
Prepare for workshop

### ISSUE THREAD

**Issue by MOJOliciousFTW** [MOJOliciousFTW/workshop-github-2024#5]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when not prepared for workshop and I don't learn anything, just waste time. Conversly, very happy when workshop prepped and anyone can pick up issues and learn.

**Describe the solution you'd like**
A repo prepared for wokshopping. Epic collab. Roadmap to great success. End goal of html site and pdf gen, anyone comfortable adding issues with note on version, discussing issues, doing work efficiently.

**Describe alternatives you've considered**
M-files workshop.

**Additional context**
If no one reminded you yet today: you're awesome.

To do:
- [x] Make a ruff plan
- [x] Make some relevant issues
- [x] Add MIT LICENCE
- [x] Add issue suggested: Add Section in readme.md called Introduction, with a short description about the repo
- [ ] Prepare for applause

**Comment by oleima** [comment]
As there will be 10+ people joining this course, we should probably have a few more Good First Issues, that can easily be done in parallel to avoid too many merge conflicts :)

So we should have lots of little good first issues for everyone to try.

I suggest:
Add MIT LICENCE
Add Section in readme.md called Introduction, with a short description about the repo

**Comment by MOJOliciousFTW** [comment]
MIT License already added https://github.com/MOJOliciousFTW/workshop-github-2024/blob/main/LICENSE

Please add suggested issues. Do you have desired access to repo?

**Comment by oleima** [comment]
I have adequate access to the repo, but I am unable to add issues to the project. Prehaps I can be granted access/premission to the project?

![image](https://github.com/user-attachments/assets/de3729a9-ff32-4da9-ba62-fbbffc192bad)

**Comment by MOJOliciousFTW** [comment]
Project access granted 👌
